dist: trusty
sudo: required

language: cpp

os:
  - linux

compiler:
    - gcc
    - valgrid

script:
  - gcc main.c -o main -std=c99
  
  - valgrind —tool=memcheck ./main
  - valgrind -v --tool=addrcheck --show-reachable=yes --leak-check=full ./main
